# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autotunnel < Formula
  desc "On-demand Kubernetes port forwarding proxy"
  homepage "https://github.com/atas/autotunnel"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.7/autotunnel_0.0.7_darwin_amd64.tar.gz"
      sha256 "86373455724e8a88c3f6487f94c3bc327948afd51339d3f2b74071356f903f72"

      def install
        bin.install "autotunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.7/autotunnel_0.0.7_darwin_arm64.tar.gz"
      sha256 "bbc1c17e80d14b59816003b295754efeda712cdcb91533b3d9370608a32c35a9"

      def install
        bin.install "autotunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.7/autotunnel_0.0.7_linux_amd64.tar.gz"
      sha256 "291400eae843978226a8251d15fc05b8dc09aec76e8f696b111f4e5ff84ca291"
      def install
        bin.install "autotunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.7/autotunnel_0.0.7_linux_arm64.tar.gz"
      sha256 "15581d0fd11c1acba76ac3852f2473e43eaaf6d58cef326ea44aabaff5c3215d"
      def install
        bin.install "autotunnel"
      end
    end
  end

  def caveats
    <<~EOS
      ---------
      To run autotunnel as a background service:
        brew services start autotunnel
      Service logs:
        tail -f $(brew --prefix)/var/log/autotunnel.log
      For manual runs:
        autotunnel
      ---------
      ⚠️ After running, edit the created 🔴 ~/.autotunnel.yaml and add your routes!!! ‼️
      Route changes will be picked up automatically.
      ---------
      ⭐🌟⭐ Please give the repo a star if useful ⭐🌟⭐
      https://github.com/atas/autotunnel
      ---------
    EOS
  end

  service do
    run [opt_bin/"autotunnel"]
    keep_alive true
    log_path var/"log/autotunnel.log"
    error_log_path var/"log/autotunnel.log"
    working_dir var
  end
end
