# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autotunnel < Formula
  desc "On-demand Kubernetes port forwarding proxy"
  homepage "https://github.com/atas/autotunnel"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.9/autotunnel_0.0.9_darwin_amd64.tar.gz"
      sha256 "4886c19f269174cddfc606ae614e41c625fb73e317f76629d6278e4f0fa26001"

      def install
        bin.install "autotunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.9/autotunnel_0.0.9_darwin_arm64.tar.gz"
      sha256 "e3ef359b6d51aea359adcce8f0de4bb81a3a1cb27bfeb0715ccf7e38418ba73e"

      def install
        bin.install "autotunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.9/autotunnel_0.0.9_linux_amd64.tar.gz"
      sha256 "4e44924a275c17efb2dd05b8026d5ec85473418d33c355dc198b6572e530b67a"
      def install
        bin.install "autotunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.9/autotunnel_0.0.9_linux_arm64.tar.gz"
      sha256 "471179b48807ff54ec6d7905613215ef1b0d83e3ecb2dc33ba688648a5445caf"
      def install
        bin.install "autotunnel"
      end
    end
  end

  def caveats
    <<~EOS
      ---------
      To run autotunnel as a background service:
        brew services start autotunnel
      Service logs:
        tail -f $(brew --prefix)/var/log/autotunnel.log
      For manual runs:
        autotunnel
      ---------
      ⚠️ After running, edit the created 🔴 ~/.autotunnel.yaml and add your routes!!! ‼️
      Route changes will be picked up automatically.
      ---------
      ⭐🌟⭐ Please give the repo a star if useful ⭐🌟⭐
      https://github.com/atas/autotunnel
      ---------
    EOS
  end

  service do
    run [opt_bin/"autotunnel"]
    keep_alive true
    log_path var/"log/autotunnel.log"
    error_log_path var/"log/autotunnel.log"
    working_dir var
  end
end
