# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autotunnel < Formula
  desc "On-demand Kubernetes port forwarding proxy"
  homepage "https://github.com/atas/autotunnel"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.8/autotunnel_0.0.8_darwin_amd64.tar.gz"
      sha256 "3ed82c5c0a7835eb5f99f64eb30d2c7529edfab440d8811dbf9f749643c2bc68"

      def install
        bin.install "autotunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.8/autotunnel_0.0.8_darwin_arm64.tar.gz"
      sha256 "44066c03860c456d0521ffa197db914f17a97ea569bccbaf9fb06e86792872e0"

      def install
        bin.install "autotunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.8/autotunnel_0.0.8_linux_amd64.tar.gz"
      sha256 "8677921121076d1eac8eec18778912045dd91fdac7f10cf26fbb39a175cdec48"
      def install
        bin.install "autotunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atas/autotunnel/releases/download/v0.0.8/autotunnel_0.0.8_linux_arm64.tar.gz"
      sha256 "7c2984572a713bda177b1c95c04ad4dff396451ae120e854804913c0502db978"
      def install
        bin.install "autotunnel"
      end
    end
  end

  def caveats
    <<~EOS
      ---------
      To run autotunnel as a background service:
        brew services start autotunnel
      Service logs:
        tail -f $(brew --prefix)/var/log/autotunnel.log
      For manual runs:
        autotunnel
      ---------
      ⚠️ After running, edit the created 🔴 ~/.autotunnel.yaml and add your routes!!! ‼️
      Route changes will be picked up automatically.
      ---------
      ⭐🌟⭐ Please give the repo a star if useful ⭐🌟⭐
      https://github.com/atas/autotunnel
      ---------
    EOS
  end

  service do
    run [opt_bin/"autotunnel"]
    keep_alive true
    log_path var/"log/autotunnel.log"
    error_log_path var/"log/autotunnel.log"
    working_dir var
  end
end
