# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyfwd < Formula
  desc "On-demand Kubernetes port forwarding proxy"
  homepage "https://github.com/atas/lazyfwd"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atas/lazyfwd/releases/download/v0.0.4/lazyfwd_0.0.4_darwin_amd64.tar.gz"
      sha256 "7f3ecbbb5dddbe7619e07f050a6d426631fa3532f83787db77a7e023b01b4554"

      def install
        bin.install "lazyfwd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atas/lazyfwd/releases/download/v0.0.4/lazyfwd_0.0.4_darwin_arm64.tar.gz"
      sha256 "80372fa87e10152db470a2f18131673433928bd4086a3b2ca57335257daa6399"

      def install
        bin.install "lazyfwd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atas/lazyfwd/releases/download/v0.0.4/lazyfwd_0.0.4_linux_amd64.tar.gz"
      sha256 "f3403ea0496742e3492a29ed97cb8f5cbe0de3649c10a8a22456e3babc9bd324"
      def install
        bin.install "lazyfwd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atas/lazyfwd/releases/download/v0.0.4/lazyfwd_0.0.4_linux_arm64.tar.gz"
      sha256 "553ae8ec439d22fe5457f7f056bbd337b0c115e617161590117aa9d7f36cc100"
      def install
        bin.install "lazyfwd"
      end
    end
  end

  def caveats
    <<~EOS
      To run lazyfwd as a background service:
        brew services start lazyfwd

      View service logs:
        tail -f $(brew --prefix)/var/log/lazyfwd.log

      For manual runs:
        lazyfwd

      ⚠️ After running, edit the created 🔴 ~/.lazyfwd.yaml and add your routes!!! ‼️
      Route changes will be picked up automatically.
    EOS
  end

  service do
    run [opt_bin/"lazyfwd"]
    keep_alive true
    log_path var/"log/lazyfwd.log"
    error_log_path var/"log/lazyfwd.log"
    working_dir var
  end
end
