# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyfwd < Formula
  desc "On-demand Kubernetes port forwarding proxy"
  homepage "https://github.com/atas/lazyfwd"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atas/lazyfwd/releases/download/v0.0.1/lazyfwd_0.0.1_darwin_amd64.tar.gz"
      sha256 "14c4b29b2a116b8587a75e22d921472249f73106e438ca6096b14a5f16324417"

      def install
        bin.install "lazyfwd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atas/lazyfwd/releases/download/v0.0.1/lazyfwd_0.0.1_darwin_arm64.tar.gz"
      sha256 "c296d1493e65a7d624fba180dbad2adbd7bf8fa31ad92610e5403bfd422a839e"

      def install
        bin.install "lazyfwd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atas/lazyfwd/releases/download/v0.0.1/lazyfwd_0.0.1_linux_amd64.tar.gz"
      sha256 "c1737aa05e57f6feb9de25ac72489cd53453b7764d9989574dc6e483fb2d0c86"
      def install
        bin.install "lazyfwd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atas/lazyfwd/releases/download/v0.0.1/lazyfwd_0.0.1_linux_arm64.tar.gz"
      sha256 "9fbcfb7e58b33ed23a7e2f7dbd1be83c6553a63274d7ef96dd501c11704003f2"
      def install
        bin.install "lazyfwd"
      end
    end
  end

  service do
    run [opt_bin/"lazyfwd"]
    keep_alive true
    log_path var/"log/lazyfwd.log"
    error_log_path var/"log/lazyfwd.log"
    working_dir var
  end
end
