# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyfwd" do
  name "lazyfwd"
  desc "On-demand Kubernetes port forwarding proxy"
  homepage "https://github.com/atas/lazyfwd"
  version "0.0.4-beta2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyfwd"

  on_macos do
    on_intel do
      url "https://github.com/atas/lazyfwd/releases/download/v#{version}/lazyfwd_#{version}_darwin_amd64.tar.gz"
      sha256 "f12f882b803db1206b32d3c973f1bbadf6d0f133a74969709835c455c64d4776"
    end
    on_arm do
      url "https://github.com/atas/lazyfwd/releases/download/v#{version}/lazyfwd_#{version}_darwin_arm64.tar.gz"
      sha256 "4603f0bc36d0af1ee381969af8dc78d488b781aa6da7004afc60ee7dd5ee62f6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/atas/lazyfwd/releases/download/v#{version}/lazyfwd_#{version}_linux_amd64.tar.gz"
      sha256 "83f15d6d83123d1e6c2f3d204b36742d6275406eed2e0d64848d0286d277f43d"
    end
    on_arm do
      url "https://github.com/atas/lazyfwd/releases/download/v#{version}/lazyfwd_#{version}_linux_arm64.tar.gz"
      sha256 "cd9a75644fe22e0bad131996677749619f51ce17a2d361cefad99367c0c4b765"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyfwd"]
  end

  caveats do
    "To run lazyfwd as a background service:"
    "  brew services start lazyfwd"
    ""
    "View service logs:"
    "  tail -f $(brew --prefix)/var/log/lazyfwd.log"
    ""
    "For manual runs:"
    "  lazyfwd"
    ""
    "⚠️ After running, edit the created 🔴 ~/.lazyfwd.yaml and add your routes!!! ‼️"
    "Route changes will be picked up automatically."
  end

  service "lazyfwd.plist"

  uninstall launchctl: [
      "com.atas.lazyfwd",
    ]

  zap trash: [
      "~/.lazyfwd.yaml",
    ]

end
