# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyfwd" do
  name "lazyfwd"
  desc "On-demand Kubernetes port forwarding proxy"
  homepage "https://github.com/atas/lazyfwd"
  version "0.0.4-beta1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyfwd"

  on_macos do
    on_intel do
      url "https://github.com/atas/lazyfwd/releases/download/v#{version}/lazyfwd_#{version}_darwin_amd64.tar.gz"
      sha256 "f23760515c776f2472c0b7339b658284472cf3deec108357beec813a6d739b0f"
    end
    on_arm do
      url "https://github.com/atas/lazyfwd/releases/download/v#{version}/lazyfwd_#{version}_darwin_arm64.tar.gz"
      sha256 "4e4a698ef4d9a454f01d77695239bfb1bd7924fd9e49d1134be77c4f07b09afe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/atas/lazyfwd/releases/download/v#{version}/lazyfwd_#{version}_linux_amd64.tar.gz"
      sha256 "2a626af34d186e66ba5b2c38ca8f379d9a88fff4c01f4054ca2ceb1c32e0d9a4"
    end
    on_arm do
      url "https://github.com/atas/lazyfwd/releases/download/v#{version}/lazyfwd_#{version}_linux_arm64.tar.gz"
      sha256 "cde561a267c9ba417d46173b5765da3586cd2d4e1e2a24a3dc7b3dbabd66ec21"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyfwd"]
  end

  caveats do
    "To run lazyfwd as a background service:"
    "  brew services start lazyfwd"
    ""
    "View service logs:"
    "  tail -f $(brew --prefix)/var/log/lazyfwd.log"
    ""
    "For manual runs:"
    "  lazyfwd"
    ""
    "⚠️ After running, edit the created 🔴 ~/.lazyfwd.yaml and add your routes!!! ‼️"
    "Route changes will be picked up automatically."
  end

  service "contrib/lazyfwd.plist"

  uninstall launchctl: [
      "com.atas.lazyfwd",
    ]

  zap trash: [
      "~/.lazyfwd.yaml",
    ]

end
