# This file was generated by GoReleaser. DO NOT EDIT.
cask "opf" do
  name "opf"
  desc "On-demand Kubernetes port forwarding proxy"
  homepage "https://github.com/atas/ondemand-port-forward"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opf"

  on_macos do
    on_intel do
      url "https://github.com/atas/ondemand-port-forward/releases/download/v#{version}/opf_#{version}_darwin_amd64.tar.gz"
      sha256 "fcb108759b910cff10bd28a7309b408f4498e9cf9ed4ca8172885034689de2bd"
    end
    on_arm do
      url "https://github.com/atas/ondemand-port-forward/releases/download/v#{version}/opf_#{version}_darwin_arm64.tar.gz"
      sha256 "5438bea354a01865afbb63224247f988c515f987423ac1baf701ee8f20d72341"
    end
  end

  # No zap stanza required
end
