# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opf < Formula
  desc "On-demand Kubernetes port forwarding proxy"
  homepage "https://github.com/atas/ondemand-port-forward"
  version "0.0.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/atas/ondemand-port-forward/releases/download/v0.0.4/opf_0.0.4_darwin_amd64.tar.gz"
    sha256 "37f39c4fdc443496443ce0d41c4a91f69c5a0ee55ab3345e289459f984df91e6"

    def install
      bin.install "opf"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/atas/ondemand-port-forward/releases/download/v0.0.4/opf_0.0.4_darwin_arm64.tar.gz"
    sha256 "7d1deaaefa8690331e14696f343f54e4714d1111516f5552a6a0dd6b305a5a93"

    def install
      bin.install "opf"
    end
  end

  test do
    system "#{bin}/opf", "--version"
  end
end
